name: Tests

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust + components
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.82
          components: rustfmt,clippy
      - name: Install Rust code coverage
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run syntax and style tests
        run: cargo clippy --all-targets -- -D warnings
      - name: Run format test
        run: cargo fmt --check
      - name: Run integration tests w/ coverage report
        run: cargo llvm-cov -- --nocapture
